"""Elimina restriccion de unicidad de ip_mask25

Revision ID: 3475eb09683b
Revises: 0af2489f5cc6
Create Date: 2025-10-01 13:46:25.266051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3475eb09683b'
down_revision = '0af2489f5cc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servidores', schema=None) as batch_op:
        batch_op.drop_constraint('uq_servidor_ip_mask25', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servidores', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_servidor_ip_mask25', ['ip_mask25'])

    # ### end Alembic commands ###
