"""empty message

Revision ID: 50066f6133f6
Revises: d908d0d1e773
Create Date: 2024-12-04 01:53:03.869172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50066f6133f6'
down_revision = 'd908d0d1e773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('img_url')

    # ### end Alembic commands ###
