"""Add estatus_id to Servidor

Revision ID: 625aa80c4a81
Revises: a1874d832354
Create Date: 2025-09-10 16:11:49.280798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625aa80c4a81'
down_revision = 'a1874d832354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servidores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estatus_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'estatus', ['estatus_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servidores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('estatus_id')

    # ### end Alembic commands ###
