"""empty message

Revision ID: 7f8d41420fb8
Revises: 
Create Date: 2025-05-06 16:02:27.017709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f8d41420fb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('capas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('dominios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('estatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('sistemas_operativos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('servidores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.Enum('FISICO', 'VIRTUAL', name='tiposervidorenum'), nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('balanceador', sa.String(length=120), nullable=True),
    sa.Column('vlan', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('link', sa.String(length=250), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('capa_id', sa.Integer(), nullable=False),
    sa.Column('ambiente_id', sa.Integer(), nullable=False),
    sa.Column('dominio_id', sa.Integer(), nullable=False),
    sa.Column('sistema_operativo_id', sa.Integer(), nullable=False),
    sa.Column('estatus_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ambiente_id'], ['ambientes.id'], ),
    sa.ForeignKeyConstraint(['capa_id'], ['capas.id'], ),
    sa.ForeignKeyConstraint(['dominio_id'], ['dominios.id'], ),
    sa.ForeignKeyConstraint(['estatus_id'], ['estatus.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.ForeignKeyConstraint(['sistema_operativo_id'], ['sistemas_operativos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('historial_servidores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servidor_id', sa.Integer(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.Enum('FISICO', 'VIRTUAL', name='tiposervidorenum'), nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('balanceador', sa.String(length=120), nullable=True),
    sa.Column('vlan', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('link', sa.String(length=250), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('servicio_nombre', sa.String(length=120), nullable=False),
    sa.Column('capa_id', sa.Integer(), nullable=False),
    sa.Column('capa_nombre', sa.String(length=120), nullable=False),
    sa.Column('ambiente_id', sa.Integer(), nullable=False),
    sa.Column('ambiente_nombre', sa.String(length=120), nullable=False),
    sa.Column('dominio_id', sa.Integer(), nullable=False),
    sa.Column('dominio_nombre', sa.String(length=120), nullable=False),
    sa.Column('sistema_operativo_id', sa.Integer(), nullable=False),
    sa.Column('sistema_operativo_nombre', sa.String(length=120), nullable=False),
    sa.Column('estatus_id', sa.Integer(), nullable=False),
    sa.Column('estatus_nombre', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['servidor_id'], ['servidores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial_servidores')
    op.drop_table('servidores')
    op.drop_table('sistemas_operativos')
    op.drop_table('servicios')
    op.drop_table('estatus')
    op.drop_table('dominios')
    op.drop_table('capas')
    op.drop_table('ambientes')
    # ### end Alembic commands ###
