"""Initial migration

Revision ID: a1874d832354
Revises: 
Create Date: 2025-09-10 15:42:17.965650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1874d832354'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambientes',
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aplicaciones',
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capas',
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dominios',
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ecosistemas',
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estatus',
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicios',
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sistemas_operativos',
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servidores',
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.Enum('FISICO', 'VIRTUAL', name='tiposervidorenum'), nullable=False),
    sa.Column('ip_mgmt', sa.String(length=50), nullable=True),
    sa.Column('ip_real', sa.String(length=50), nullable=True),
    sa.Column('ip_mask25', sa.String(length=50), nullable=True),
    sa.Column('balanceador', sa.String(length=120), nullable=True),
    sa.Column('vlan', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('link', sa.String(length=250), nullable=True),
    sa.Column('ecosistema_id', sa.Integer(), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('capa_id', sa.Integer(), nullable=False),
    sa.Column('ambiente_id', sa.Integer(), nullable=False),
    sa.Column('dominio_id', sa.Integer(), nullable=False),
    sa.Column('sistema_operativo_id', sa.Integer(), nullable=False),
    sa.Column('aplicacion_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ambiente_id'], ['ambientes.id'], ),
    sa.ForeignKeyConstraint(['aplicacion_id'], ['aplicaciones.id'], ),
    sa.ForeignKeyConstraint(['capa_id'], ['capas.id'], ),
    sa.ForeignKeyConstraint(['dominio_id'], ['dominios.id'], ),
    sa.ForeignKeyConstraint(['ecosistema_id'], ['ecosistemas.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.ForeignKeyConstraint(['sistema_operativo_id'], ['sistemas_operativos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_mask25', name='uq_servidor_ip_mask25'),
    sa.UniqueConstraint('ip_mgmt', name='uq_servidor_ip_mgmt'),
    sa.UniqueConstraint('ip_real', name='uq_servidor_ip_real'),
    sa.UniqueConstraint('nombre', name='uq_servidor_nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servidores')
    op.drop_table('sistemas_operativos')
    op.drop_table('servicios')
    op.drop_table('estatus')
    op.drop_table('ecosistemas')
    op.drop_table('dominios')
    op.drop_table('capas')
    op.drop_table('aplicaciones')
    op.drop_table('ambientes')
    # ### end Alembic commands ###
