"""empty message

Revision ID: a78e35de37dc
Revises: 7032b3c8da78
Create Date: 2024-11-05 17:32:33.114375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a78e35de37dc'
down_revision = '7032b3c8da78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', postgresql.ENUM('PATIENT', 'DOCTOR', 'MANAGER', name='roleenum'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
