"""mensaje

Revision ID: b0c7ed4a46c8
Revises: 3475eb09683b
Create Date: 2025-11-11 14:31:52.862103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c7ed4a46c8'
down_revision = '3475eb09683b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servidores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vlan_mgmt', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('vlan_real', sa.String(length=50), nullable=True))
        batch_op.alter_column('aplicacion_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servidores', schema=None) as batch_op:
        batch_op.alter_column('aplicacion_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('vlan_real')
        batch_op.drop_column('vlan_mgmt')

    # ### end Alembic commands ###
