"""Add servidor_aplicacion association table

Revision ID: e867f6dc228a
Revises: 625aa80c4a81
Create Date: 2025-09-12 09:49:51.600032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e867f6dc228a'
down_revision = '625aa80c4a81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servidor_aplicacion',
    sa.Column('servidor_id', sa.Integer(), nullable=False),
    sa.Column('aplicacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aplicacion_id'], ['aplicaciones.id'], ),
    sa.ForeignKeyConstraint(['servidor_id'], ['servidores.id'], ),
    sa.PrimaryKeyConstraint('servidor_id', 'aplicacion_id')
    )
    with op.batch_alter_table('servidores', schema=None) as batch_op:
        batch_op.drop_constraint('servidores_aplicacion_id_fkey', type_='foreignkey')
        batch_op.drop_column('aplicacion_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servidores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aplicacion_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('servidores_aplicacion_id_fkey', 'aplicaciones', ['aplicacion_id'], ['id'])

    op.drop_table('servidor_aplicacion')
    # ### end Alembic commands ###
